name: Build and Release

on:
  push:
    branches:
      - main
      - DVD-Logo

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: dotnet publish -c Release -o output  -p:PublishSingleFile=true
        
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ runner.os }}-release-$(date +%Y-%m-%d)
          body: 'Release built by GitHub Actions'
          draft: true
          prerelease: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: output/*.exe
